### ISSUE TITLE
Update site and setup tito for April 1st

### ISSUE THREAD

**Issue by ashwell** [nodeschool/los-angeles#105]
### Todos ###
- [x] Setup tickets
- [ ] Confirm Codesmith as host
- [ ] Update Repo
- [ ] Create "Calling all Mentors" issue
- [ ] Update gh-pages branch
- [ ] Add to nodeschool's events page
