### ISSUE TITLE
Update site and setup tito for May 1st #109

### ISSUE THREAD

**Issue by rouzbeh84** [nodeschool/los-angeles#110]
### Todos ###
- [x] Setup tickets
- [x] Confirm Codesmith as host
- [x] Update Readme
- [x] Create "Calling all Mentors" issue
- [x] Update gh-pages branch
- [x] Add to nodeschool's events page

**Comment by rouzbeh84** [comment]
all set. opening checklist issue now
