### ISSUE TITLE
Organizer / Mentor checklist and tips for 7/25/2015 event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#29]
For all those involved in coordinating and mentoring, please look below and mark if you can assist with any of the following. Below are some tips for mentoring as well if this is your first time.

**Mentors**
* @d48
* @davidguttman (Will be MC for the event)
* @8bitDesigner (Fullscreen sponsorship)
* @rynodivino
* @paigeful
* @aktary
* @soldair
* @emkay
* @xbudex
* @dstokes
* @WillSen (Codesmith sponsor/talk)

## Food & Amenities
- [x]  Person(s) that are purchasing food and drink. Ask me (@d48) for ti.to ticket answers for diet restrictions
- [ ]  Label food options and those with allergens.  Vegan, Gluten-free

## Workshop Prep
- [ ] Pre-package some workshops on a couple USB sticks for access or on a local IP address. We can’t rely on the internet.
- [x] Name tags and markers. 
- [x] Something to denote a mentor so attendees can easily spot and inquire
- [ ] Portable projector. In case SmartBoard can not project from computer

## Mentoring Tips
* **Do a workshopper**: Make sure you have done at least **learnyounode** so you can help others
* **Hover**: Mentors float around the event asking attendees if they are stuck, or if the attendees are too scared to ask for help then the mentors would try to peak over their shoulders and give them unsolicited advice.
* **Troubleshooting** : Don't give answers straight away if you know the bug or problem they are trying to solve. Instead guide them through the debugging process as this helps:
  1. Make the learner feel less incompetent and more like we're in this together because we both don't know what's going on, and 
  2. Give them the skills to find their own bugs when there aren't mentors around.
* And read through this thorough guide from the San Francisco chapter: https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice

## Schedule (tenative)
| Name | Time          | Description |
| :--- | :--- | :--- |
| Pre-event      | 1:30pm - 2:00pm | Will Sentance talk |
| Check-in     | 2:00pm - 2:30pm     | Check list and hand out name tags, marker to write |
| Snack / Drink | 2:30pm - 3:00pm | Food and refreshments before we start |
| MC Welcome / Overview | 3:00pm - 3:10pm | Introduction and explain general setup of workshop install and mentor access |
| Workshop start | 3:10pm | Attendees installing/learning and asking mentors questions |
| Break | 4:10pm | Bio break and stretch |
| Workshop end | 5:30pm | Let attendees know about 30 minutes. Final help and clean up |
| After event | 6:00pm - ? | Drinks with Codesmith sponsoring |

**Comment by kimmark** [comment]
Hi ryan! I'm on the waitlist for this Saturday's workshop. Really interested in this and if there's anything I can do to help, let me know! I'm close to the area so I can do errands or anything if needed!

**Comment by d48** [comment]
Thank for your interest Mark. If we can accommodate those on the list you should get an email by end of day today. Thanks for your willingness to help! I'll let you know by this evening

**Comment by d48** [comment]
Mentors, we will be arriving an hour earlier or so to get situated, 1pm or earlier. Feel free to come by any time to help set up and/or hang out.

**Comment by d48** [comment]
Thank you everyone, what a great Saturday event! Anyone up for a post-write up? All mentors, we need your feedback to make the next one even greater. Please fill out this google form when you get a moment: http://goo.gl/forms/plc8F4DmBZ
