### ISSUE TITLE
Organizer / Mentor checklist and tips for 8/22/2015 event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#38]
For all those involved in coordinating and mentoring, please review items below. There are some tips for mentoring as well if this is your first time.

**Mentors**
* @d48 (MC for the event)
* @jcblw
* @upinthisjoynt
* @jnutter 
* @8bitDesigner 
* @xbudex

Note: please arrive by 1:30pm to help with any setup and to get an overview of the day's event

## Food & Amenities
- [ ]  Food and drink delivery, let delivery up
- [ ] Set up food tables and plates/cups/napkins
- [ ]  Label food options: Vegan, Gluten-free
- [ ] Ice and bucket

## Workshop Prep
- [ ] Name tags and markers. Stickers to denote mentors
- [ ] Overview with mentors what to expect and what is expected of them

## Mentoring Tips
* **Do a workshopper**: Make sure you have done at least **learnyounode** so you can help others
* **Hover**: Mentors float around the event asking attendees if they are stuck, or if the attendees are too scared to ask for help then the mentors would try to peak over their shoulders and give them unsolicited advice.
* **Troubleshooting** : Don't give answers straight away if you know the bug or problem they are trying to solve. Instead guide them through the debugging process as this helps:
  1. Make the learner feel less incompetent and more like we're in this together because we both don't know what's going on, and 
  2. Give them the skills to find their own bugs when there aren't mentors around.
* And read through this thorough guide from the San Francisco chapter: https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice

## Schedule 
| Name | Time          | Description |
| :--- | :--- | :--- |
| Event setup     | 1:00pm - 2:00pm  | Table setup, signage, slide on projector, music, food, name tags and marker, table blocking certain entry ways |
| Check-in     | 1:30pm - 2:30pm     | Check list and hand out name tags, marker to write |
| Snack / Drink | 2:00pm - 2:30pm | Food and refreshments before we start |
| MC Welcome / Overview | 2:30pm - 2:40pm | Introduction and explain general setup of workshop install, workshoppers overview, mentor access |
| Workshop start | 2:40pm - 5:30pm | Attendees installing/learning and asking mentors questions |
| Workshop end, Group Pic | 5:30pm | Let attendees know about 30 minutes Nodeschool will end. Group picture. Final help and clean up |
| Clean up | 5:30pm - 6:00pm | Be ready before end of time and show appreciation for people coming out to learn |

**Comment by d48** [comment]
Thanks @machikoyasuda, even better mentor prep article from [nodeschool/sanfrancisco](https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice)

**Comment by d48** [comment]
Fantastic job you guys. The day went really well
