### ISSUE TITLE
Event / Mentor checklist for 5/7/2016 Event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#73]
## Mentors
Below are some tips for mentoring as well if this is your first time. Thanks for your willingness to help and contribute to the community.

@d48
@etanlubeck
@upinthisjoynt
@jcblw
@ashwell
@marksanghoonkim

## Food & Amenities
- [x] Order and have delivered before event starts. @d48 

## Workshop Prep
- [x] Name tags and markers. @d48 

## MC for the event
- [x] Welcome and script. https://github.com/nodeschool/los-angeles/wiki/Announcements-Script-for-day-of-event @jcblw 

## Overview of Node.js
- [x] Node.js overview and samples uses. @ashwell 

## Mentoring Tips
* **Do a workshopper**: Make sure you have done at least **learnyounode** so you can help others
* **Hover**: Mentors float around the event asking attendees if they are stuck, or if the attendees are too scared to ask for help then the mentors would try to peak over their shoulders and give them unsolicited advice.
* **Troubleshooting** : Don't give answers straight away if you know the bug or problem they are trying to solve. Instead guide them through the debugging process as this helps:
  1. Make the learner feel less incompetent and more like we're in this together because we both don't know what's going on, and 
  2. Give them the skills to find their own bugs when there aren't mentors around.
* And read through this thorough guide from the San Francisco chapter: https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice
* **Organizing attendees**: Based on previous feedback, attendees would feel comfortable and can potentially perform better if grouped together with people doing the same workshoppers. If we can, setting up tables in a triangle has worked very well in the past. We will have a show of hands of which attendees will be doing what and we will do a seating shuffle at that point.

## Schedule (tenative)
| Name | Time          | Description |
| :--- | :--- | :--- |
| Mentors check-in      | 1:30pm - 1:45pm | Come a little early if possible. Will review with how we will organize attendees based on workshopper/experience.  |
| Check-in / Snack and drink     | 2:00pm - 2:30pm     | Check list and hand out name tags, marker to write, Food and refreshments before we start (@d48) |
| MC Welcome / Overview | 2:15pm - 2:30pm | Introduction and explain general setup of workshop install and mentor access (@jcblw). Also Sponsor intro for 5 minutes: CodeSmith. Node.js overview and sample uses (@ashwell)  |
| Workshop start | 2:30pm | Attendees installing/learning and asking mentors questions |
| Group pic | 4:30pm | Take a picture! |
| Workshop end | 5:30pm | Let attendees know about 30 minutes. Final help and clean up. |
| Finish | 6:00pm | Go home |

**Comment by d48** [comment]
good job you guys! closing this to setup for next months
